#!/usr/bin/env bash

# Install Flatpak
echo "Enabling flatpak"
sudo dnf install -y flatpak
# Enable the Flathub remote
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install packages
echo "Installing packages"
packages=(
    bat
    brightnessctl
    cmake
    direnv
    dmenu
    docker-compose
    fastfetch
    firefox
    fzf
    gh
    golang
    hyprland
    hypridle
    hyprlock
    lazygit
    libnotify
    neovim
    network-manager-applet
    pavucontrol
    pipewire-pulseaudio
    ripgrep
    rofi-wayland
    stow
    swayimg
    SwayNotificationCenter
    swww
    tlp
    tmux
    tree
    fontawesome-fonts-all
    unzip
    waybar
    wl-clipboard
    yad
    zoxide
    zsh
    man-pages
    wlogout
    python3
    material-icons-fonts
)

for package in "${packages[@]}"
do
    sudo dnf install ${package} -y
done

# Copr packages
echo "Intsalling copr packages"
sudo dnf copr enable sneexy/zen-browser -y
sudo dnf install zen-browswer -y

sudo dnf copr enable materka/swww -y
sudo dnf install swww -y

sudo dnf copr enable atim/starship -y
sudo dnf install starship -y

sudo dnf copr enable atim/lazygit -y
sudo dnf install lazygit -y

sudo dnf copr enable pgdev/ghostty -y
sudo dnf install ghostty -y

# Install Flatpak pacakges
echo "Installing Flatpak packages"
flatpak install flathub com.spotify.Client
flatpak run cc.arduino.IDE2
echo "Arduino: adding user to dialout group"
sudo usermod -a -G dialout $USER

# Fonts
echo "Installing fonts"
fonts=(
    fontawesome-fonts-all
    google-noto-sans-cjk-fonts
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    jetbrains-mono-fonts
)

for font in "${fonts[@]}"
do
    sudo dnf install ${font} -y
done

# Zsh plugins
echo "Installing zsh plugins"
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting

# Tmux plugin sesh
echo "Installing tmux plugins"
go install github.com/joshmedeski/sesh/v2@latest

# packages to figure out how to install
# arduino-cli arduino-ide discord lf nerd-fonts wakeonlan ghostty tlpui trashy

# Install yay packages
#yay -S rustmon-git spotify tlpui trashy ttf-material-icons-git

# Make some directories
echo "Creating directories"
mkdir -p ~/workspaces/github.com/CodyBense
mkdir -p ~/workspaces/Projects

# Stow commands for dotfiles
echo "Using stow to create dotflies"
cd ~/dotfiles
stow emoji
stow git
stow hypr
stow kitty
stow lf
stow nvim
stow rofi
stow scripts
stow starship
stow swaync
stow tmux
stow wallpapers
stow waybar
stow wlogout
stow zsh
stow ghostty
