#!/usr/bin/env bash

# choose shell
echo "Do you want to use zsh or bash"
read shell

# Install Flatpak
echo "Enabling flatpak"
sudo dnf install -y flatpak
# Enable the Flathub remote
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install packages
echo "Installing packages"
packages=(
    bat
    brightnessctl
    btop
    cifs-utils
    cmake
    direnv
    dmenu
    docker-compose
    fastfetch
    firefox
    fzf
    gcc
    gh
    git
    golang
    hyprland
    hypridle
    hyprlock
    hyprpicker
    kicad
    killall
    kitty
    libnotify
    man-pages
    neovim
    NetworkManager
    network-manager-applet
    pavucontrol
    pipewire-pulseaudio
    power-profiles-daemon
    psmisc
    python3
    ripgrep
    rofi-wayland
    rsync
    stow
    swayimg
    SwayNotificationCenter
    swww
    tlp
    tmux
    tree
    unzip
    uv
    waybar
    wf-recorder
    wget
    wl-clipboard
    wlogout
    yad
    zoxide
    zsh
)

for package in "${packages[@]}"
do
    sudo dnf install ${package} -y
done

# Copr packages
echo "Intsalling copr packages"
sudo dnf copr enable sneexy/zen-browser -y
sudo dnf install zen-browswer -y

sudo dnf copr enable materka/swww -y
sudo dnf install swww -y

sudo dnf copr enable atim/starship -y
sudo dnf install starship -y

sudo dnf copr enable atim/lazygit -y
sudo dnf install lazygit -y

sudo dnf copr enable pgdev/ghostty -y
sudo dnf install ghostty -y

sudo dnf copr enable varlad/zellij 
sudo dnf install zellij

# Install Flatpak pacakges
echo "Installing Flatpak packages"
flatpak install flathub com.spotify.Client
flatpak run cc.arduino.IDE2
flatpak install flathub md.obsidian.Obsidian
flatpak run io.github.sxyazi.yazi
echo "Arduino: adding user to dialout group"
sudo usermod -a -G dialout $USER

# Fonts
echo "Installing fonts"
fonts=(
    fontawesome-fonts-all
    google-noto-sans-cjk-fonts
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    jetbrains-mono-fonts
    material-icons-fonts
)

for font in "${fonts[@]}"
do
    sudo dnf install ${font} -y
done


# Tmux plugin sesh
echo "Installing tmux plugins"
go install github.com/joshmedeski/sesh/v2@latest

# packages to figure out how to install
# discord lf wakeonlan tlpui trashy

# Install yay packages
#yay -S rustmon-git tlpui trashy ttf-material-icons-git

# Make some directories
echo "Creating directories"
if [ ! -d ~/workspaces/github.com/CodyBense ]; then
    mkdir -p ~/workspaces/github.com/CodyBense
fi

if [ ! -d ~/workspaces/Projects ]; then
    mkdir -p ~/workspaces/Projects
fi

if [ ! -d ~/HOME/Documents/Notes ]; then
    mkdir -p ~/Documents/Notes
fi

# Stow commands for dotfiles
echo "Using stow to source dotflies"
cd ~/dotfiles
dirs=(
    emoji
    git
    hypr
    lf
    nvim
    rofi
    scripts
    starship
    swaync
    tmux
    wallpapers
    waybar
    wlogout
    ghostty
)

for dir in "${dirs[@]}"
do
    stow ${dir}
done

# Zsh stuff
if [ "$shell" = "zsh" ]; then
    # Zsh plugins
    echo "Installing zsh plugins"
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
    echo "Chaning shell to zsh"
    chsh -s /bin/zsh $USER
    stow zsh
fi

if [ "$shell" = "bash" ]; then
    stow bash
fi

echo "Completed setup"
