[ids]

*

[main]

capslock = esc

a = overloadi(a, overloadt2(meta, a, 200), 150)
s = overloadi(s, overloadt2(alt, s, 200), 150)
d = overloadi(d, overloadt2(shift, d, 200), 150)
f = overloadi(f, overloadt2(control, f, 200), 150)

; = overloadi(;, overloadt2(meta, ;, 200), 150)
l = overloadi(l, overloadt2(alt, l, 200), 150)
k = overloadi(k, overloadt2(shift, k, 200), 150)
j = overloadi(j, overloadt2(control, j, 200), 150)
