unbind C-b
unbind-key -a
# unbind '"'
# unbind %
# unbind r

bind-key C-s send-prefix
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key "h" split-window -v
bind-key "v" split-window -h
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-x kill-pane
bind -n M-V split-window -h
bind -n M-H split-window -v
bind r command-prompt "rename-window %%"
bind R source-file $HOME/.tmux.conf
bind g run "$HOME/bin/open-git.sh"
