source-file ~/.tmux.reset.conf
set -g default-command "${SHELL}"

ctp_bg="#24273a"
ctp_surface_1="#494d64"
ctp_fg="#cad3f5"
ctp_mauve="#c6a0f6"
ctp_pink="#f5c2e7"
ctp_green="#a6e3a1"
ctp_crust="#181926"

set -g prefix C-s
set -g base-index 1
# set -g detach-on-destory off
set -g escape-time 0
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
setw -g mode-keys vi
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${ctp_fg},bg=${ctp_bg}"
set -g status-left "#[fg=${ctp_mauve},bold]  #S #[fg=${ctp_fg},nobold]| "
set -g status-right "#[fg=${ctp_green},bold]%H:%M"
set -g window-status-current-format "#[fg=${ctp_pink}, bold] #I:#W"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.tmux/plugins/tpm/tpm'
